//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELO
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUDITORIA_LOGIN
    {
        public int Id_Auditoria_Login { get; set; }
        public System.DateTime Entrada { get; set; }
        public Nullable<System.DateTime> Salida { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
