//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CATALOGO : DbContext
    {
        public CATALOGO()
            : base("name=CATALOGO")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<USUARIO> USUARIOS { get; set; }
        public virtual DbSet<MODULO> MODULOS { get; set; }
        public virtual DbSet<SUBMODULO> SUBMODULOS { get; set; }
        public virtual DbSet<FORMULARIO> FORMULARIOS { get; set; }
        public virtual DbSet<ACCION> ACCIONES { get; set; }
        public virtual DbSet<GRUPO> GRUPOS { get; set; }
        public virtual DbSet<AUDITORIA_LOGIN> AUDITORIAS_LOGIN { get; set; }
        public virtual DbSet<CLIENTE> CLIENTES { get; set; }
        public virtual DbSet<FACTURA> FACTURAS { get; set; }
        public virtual DbSet<PRODUCTO> PRODUCTOS { get; set; }
        public virtual DbSet<MOVIMIENTO> MOVIMIENTOS { get; set; }
        public virtual DbSet<RECIBO> RECIBOS { get; set; }
        public virtual DbSet<NOTA_CREDITO> NOTAS_CREDITO { get; set; }
        public virtual DbSet<CAJA> CAJAS { get; set; }
        public virtual DbSet<MOVIMIENTO_CAJA> MOVIMIENTOS_CAJA { get; set; }
        public virtual DbSet<FORMA_DE_PAGO> FORMAS_DE_PAGOS { get; set; }
        public virtual DbSet<DETALLE_FACTURA> DETALLES_FACTURA { get; set; }
        public virtual DbSet<TARJETA> TARJETAS { get; set; }
    }
}
