//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_FACTURA
    {
        public int id_Factura { get; set; }
        public int Codigo_Producto { get; set; }
        public decimal Cantidad { get; set; }
        public decimal Precio { get; set; }
    
        public virtual FACTURA FACTURA { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
