//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELO
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIMIENTO
    {
        public int Id_Movimiento { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Tipo_Comprobante { get; set; }
        public Nullable<int> Nro_Comprobante { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Facturado { get; set; }
        public decimal Pagado { get; set; }
        public int id_Cliente { get; set; }
        public Nullable<decimal> Importe_Cancelado { get; set; }
        public decimal Saldo { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
    }
}
