//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELO
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIMIENTO_CAJA
    {
        public int Id_Movimiento { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Concepto { get; set; }
        public string Comprobante { get; set; }
        public int Número_Comprobante { get; set; }
        public string Forma_de_Pago { get; set; }
        public decimal Entrada { get; set; }
        public decimal Salida { get; set; }
    
        public virtual CAJA CAJA { get; set; }
    }
}
